# Generated by Django 5.0.4 on 2024-06-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0003_alter_store_last_modified_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ["create_at"]},
        ),
    ]
