# Generated by Django 5.0.4 on 2024-06-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-create_at"]},
        ),
    ]
