# Generated by Django 5.0.4 on 2024-06-14 21:19

import django.core.validators
import django.db.models.deletion
import utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_customer", "0001_initial"),
        ("app_driver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactorItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "price",
                    utils.db.fields.PriceField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price",
                    ),
                ),
                (
                    "tax",
                    utils.db.fields.PercentField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Tax",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Count",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FactorPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="پاک شده"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پاک شدن"
                    ),
                ),
                (
                    "amount",
                    utils.db.fields.PriceField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("check", "Check"),
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                        ],
                        default="cash",
                        max_length=11,
                        verbose_name="Payment Type",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Tracking Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "ordering": ["-create_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="پاک شده"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پاک شدن"
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Tracking Code",
                    ),
                ),
                ("factor_date", models.DateField(verbose_name="Factor Date")),
                (
                    "discount_is_percent",
                    models.BooleanField(
                        default=False, verbose_name="Discount Is Percent"
                    ),
                ),
                (
                    "discount_value",
                    utils.db.fields.PriceField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Discount Value",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(default=True, verbose_name="Is Accepted"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "payment_status",
                    models.BooleanField(default=False, verbose_name="Payment Status"),
                ),
                (
                    "permission_for_accept",
                    models.CharField(
                        choices=[
                            ("superuser_staff", "Superuser Or Staff"),
                            (
                                "secretary_superuser_staff",
                                "Secretary Or Superuser Or Staff",
                            ),
                        ],
                        default="secretary_superuser_staff",
                        max_length=25,
                        verbose_name="Permission For Accept",
                    ),
                ),
                (
                    "payment_amount",
                    utils.db.fields.PriceField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Payment Amount",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_address_factors",
                        to="app_customer.customeraddress",
                        verbose_name="Address",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_factors",
                        to="app_customer.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_factors",
                        to="app_driver.driver",
                        verbose_name="Driver",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_at"],
                "abstract": False,
            },
        ),
    ]
