# Generated by Django 5.0.4 on 2024-06-14 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_factor", "0001_initial"),
        ("app_product", "0001_initial"),
        ("app_store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="factor",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AddField(
            model_name="factor",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store_factors",
                to="app_store.store",
                verbose_name="Store",
            ),
        ),
        migrations.AddField(
            model_name="factoritems",
            name="factor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factor_items",
                to="app_factor.factor",
                verbose_name="Factor",
            ),
        ),
        migrations.AddField(
            model_name="factoritems",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AddField(
            model_name="factoritems",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_factors",
                to="app_product.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="factorpayments",
            name="factor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factor_payments",
                to="app_factor.factor",
                verbose_name="Factor",
            ),
        ),
        migrations.AddField(
            model_name="factorpayments",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
    ]
