# Generated by Django 5.0.4 on 2024-06-26 14:16

import app_factor.models.factor
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_factor", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="factor",
            name="factor_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app_factor.models.factor.factor_file_directory_path,
                verbose_name="Factor File",
            ),
        ),
        migrations.AlterField(
            model_name="factor",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخرین تغییر توسط",
            ),
        ),
        migrations.AlterField(
            model_name="factoritems",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخرین تغییر توسط",
            ),
        ),
        migrations.AlterField(
            model_name="factorpayments",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخرین تغییر توسط",
            ),
        ),
    ]
