# Generated by Django 5.0.4 on 2024-06-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_factor",
            "0003_factor_factor_file_alter_factor_last_modified_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factor",
            options={"ordering": ["create_at"]},
        ),
        migrations.AlterModelOptions(
            name="factoritems",
            options={"ordering": ["create_at"]},
        ),
        migrations.AlterModelOptions(
            name="factorpayments",
            options={"ordering": ["create_at"]},
        ),
    ]
