# Generated by Django 5.0.4 on 2024-06-01 07:36

import datetime
import django.core.validators
import django.db.models.deletion
import utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_factor", "0003_factor_permission_for_accept"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factor",
            options={"ordering": ["-create_at"]},
        ),
        migrations.AlterModelOptions(
            name="factoritems",
            options={"ordering": ["-create_at"]},
        ),
        migrations.RemoveField(
            model_name="factor",
            name="marketer",
        ),
        migrations.AddField(
            model_name="factor",
            name="discount_is_percent",
            field=models.BooleanField(
                default=False, verbose_name="Discount Is Percent"
            ),
        ),
        migrations.AddField(
            model_name="factor",
            name="discount_value",
            field=utils.db.fields.PriceField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Discount Value",
            ),
        ),
        migrations.AddField(
            model_name="factor",
            name="factor_date",
            field=models.DateField(
                default=datetime.date(2024, 6, 1), verbose_name="Factor Date"
            ),
        ),
        migrations.CreateModel(
            name="FactorPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "amount",
                    utils.db.fields.PriceField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factor_payments",
                        to="app_factor.factor",
                        verbose_name="Factor",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_at"],
                "abstract": False,
            },
        ),
    ]
