# Generated by Django 5.0.4 on 2024-06-04 08:23

import django.core.validators
import utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_factor", "0004_alter_factor_options_alter_factoritems_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factor",
            name="payment_type",
        ),
        migrations.AddField(
            model_name="factor",
            name="payment_amount",
            field=utils.db.fields.PriceField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Payment Amount",
            ),
        ),
        migrations.AlterField(
            model_name="factor",
            name="factor_date",
            field=models.DateField(verbose_name="Factor Date"),
        ),
    ]
