# Generated by Django 5.0.4 on 2024-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_factor",
            "0005_remove_factor_payment_type_factor_payment_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="factor",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted Time"
            ),
        ),
        migrations.AddField(
            model_name="factor",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Is Deleted"
            ),
        ),
        migrations.AddField(
            model_name="factoritems",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted Time"
            ),
        ),
        migrations.AddField(
            model_name="factoritems",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Is Deleted"
            ),
        ),
        migrations.AddField(
            model_name="factorpayments",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted Time"
            ),
        ),
        migrations.AddField(
            model_name="factorpayments",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Is Deleted"
            ),
        ),
    ]
