# Generated by Django 5.0.4 on 2024-06-09 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_factor", "0006_factor_deleted_at_factor_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factorpayments",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="factorpayments",
            name="payment_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Payment Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factorpayments",
            name="payment_type",
            field=models.CharField(
                choices=[("check", "Check"), ("cash", "Cash"), ("bank", "Bank")],
                default="cash",
                max_length=11,
                verbose_name="Payment Type",
            ),
        ),
        migrations.AddField(
            model_name="factorpayments",
            name="tracking_code",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Tracking Code"
            ),
        ),
    ]
