# Generated by Django 5.0.4 on 2024-06-13 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_driver", "0001_initial"),
        ("app_factor", "0007_factorpayments_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factor",
            name="driver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_factors",
                to="app_driver.driver",
                verbose_name="Driver",
            ),
            preserve_default=False,
        ),
    ]
