# Generated by Django 5.0.4 on 2024-06-13 09:13

import django.core.validators
import utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Is Deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "mobile_number",
                    utils.db.fields.PhoneField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^{?(0?9[0-9]{9,9}}?)$", "Invalid Mobile Number Format"
                            )
                        ],
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=124, verbose_name="Full Name"),
                ),
                (
                    "plate_number",
                    models.CharField(max_length=20, verbose_name="Plate Number"),
                ),
            ],
            options={
                "ordering": ["-create_at"],
                "abstract": False,
            },
        ),
    ]
