# Generated by Django 5.0.4 on 2024-06-26 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_driver", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="state",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخرین تغییر توسط",
            ),
        ),
    ]
