# Generated by Django 5.0.4 on 2024-06-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_driver", "0003_driver_state_alter_driver_last_modified_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["create_at"]},
        ),
    ]
