# Generated by Django 5.0.4 on 2024-06-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_driver", "0004_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["-create_at"]},
        ),
    ]
