# Generated by Django 5.0.4 on 2024-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0001_initial"),
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stores",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="store_users",
                to="app_store.store",
                verbose_name="Stores",
            ),
        ),
    ]
