# Generated by Django 5.0.4 on 2024-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0001_initial"),
        ("app_user", "0002_user_stores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="stores",
            field=models.ManyToManyField(
                related_name="store_users", to="app_store.store", verbose_name="Stores"
            ),
        ),
    ]
