# Generated by Django 5.0.4 on 2024-05-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0001_initial"),
        ("app_user", "0004_alter_user_stores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="stores",
            field=models.ManyToManyField(
                blank=True,
                related_name="store_users",
                to="app_store.store",
                verbose_name="Stores",
            ),
        ),
    ]
