# Generated by Django 5.0.4 on 2024-04-09 20:22

import django.core.validators
import django.db.models.deletion
import utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "mobile_number",
                    utils.db.fields.PhoneField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^{?(0?9[0-9]{9,9}}?)$", "Invalid Mobile Number Format"
                            )
                        ],
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=124, verbose_name="Full Name"),
                ),
                (
                    "customer_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Customer Code"
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="National Code"
                    ),
                ),
            ],
            options={
                "ordering": ["create_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("country", models.CharField(max_length=32, verbose_name="Country")),
                ("state", models.CharField(max_length=32, verbose_name="State")),
                ("full_address", models.TextField(verbose_name="Full Address")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_addresses",
                        to="app_customer.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "ordering": ["create_at"],
                "abstract": False,
            },
        ),
    ]
