# Generated by Django 5.0.4 on 2024-06-14 21:19

import django.core.validators
import utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="پاک شده"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پاک شدن"
                    ),
                ),
                (
                    "mobile_number",
                    utils.db.fields.PhoneField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^{?(0?9[0-9]{9,9}}?)$", "فرمت شماره موبایل اشتباه است"
                            )
                        ],
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=124, verbose_name="Full Name"),
                ),
                (
                    "customer_code",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="Customer Code"
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="National Code",
                    ),
                ),
                (
                    "marketer",
                    models.CharField(
                        blank=True, max_length=124, null=True, verbose_name="Marketer"
                    ),
                ),
            ],
            options={
                "ordering": ["-create_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="پاک شده"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پاک شدن"
                    ),
                ),
                ("country", models.CharField(max_length=32, verbose_name="Country")),
                ("state", models.CharField(max_length=32, verbose_name="State")),
                ("city", models.CharField(max_length=32, verbose_name="City")),
                ("street", models.CharField(max_length=32, verbose_name="Street")),
                ("full_address", models.TextField(verbose_name="Full Address")),
            ],
            options={
                "ordering": ["-create_at"],
                "abstract": False,
            },
        ),
    ]
