# Generated by Django 5.0.4 on 2024-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Customer Code",
            ),
        ),
    ]
