# Generated by Django 5.0.4 on 2024-05-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_customer", "0002_alter_customer_customer_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraddress",
            name="city",
            field=models.CharField(default=2, max_length=32, verbose_name="City"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="street",
            field=models.CharField(default=2, max_length=32, verbose_name="Street"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_addresses",
                to="app_customer.customer",
                verbose_name="Customer",
            ),
        ),
    ]
