# Generated by Django 5.0.4 on 2024-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_customer", "0004_alter_customer_options_alter_customeraddress_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="marketer",
            field=models.CharField(
                blank=True, max_length=124, null=True, verbose_name="Marketer"
            ),
        ),
    ]
