# Generated by Django 5.0.4 on 2024-06-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_customer", "0004_alter_customer_options_alter_customeraddress_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-create_at"]},
        ),
        migrations.AlterModelOptions(
            name="customeraddress",
            options={"ordering": ["-create_at"]},
        ),
    ]
