# Generated by Django 5.0.4 on 2024-06-04 16:48

import django.core.validators
import utils.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_customer", "0005_customer_marketer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile_number",
            field=utils.db.fields.PhoneField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^{?(0?9[0-9]{9,9}}?)$", "Invalid Mobile Number Format"
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="national_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="National Code"
            ),
        ),
    ]
