# Generated by Django 5.0.4 on 2024-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_customer", "0006_alter_customer_mobile_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted Time"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Is Deleted"
            ),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted Time"
            ),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Is Deleted"
            ),
        ),
    ]
