# Generated by Django 5.0.4 on 2024-06-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_customer", "0007_customer_deleted_at_customer_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_code",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Customer Code"
            ),
        ),
    ]
